manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: petejohanson
      revision: afda1561bf9aeb4cb74f709acc8bf61f809450ea
      import: app/west.yml
  self:
    path: config
